name: project_shop
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  dot_curved_bottom_nav: ^0.0.2
  curved_navigation_bar: ^1.0.6
  curved_labeled_navigation_bar: ^2.0.6
  firebase_core: ^3.11.0
  cloud_firestore: ^5.6.3
  badges: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - images/

